FROM node:6.9.1
RUN mkdir -p /usr/src/sportsstore
COPY dist /usr/src/sportsstore/app
COPY
COPY
COPY
COPY
authMiddleware.js /usr/src/sportsstore/
data.js /usr/src/sportsstore/
deploy-server.js /usr/src/sportsstore/server.js
deploy-package.json /usr/src/sportsstore/package.json
WORKDIR /usr/src/sportsstore
RUN npm install
EXPOSE 3000
EXPOSE 3500
CMD ["npm", "start"]
